### PR TITLE
feat: add CookieAccessInfo.All sentinel

### LINKED ISSUE #24: Provide facility for retrieving all cookies; a wildcard CookieAccessInfo
Hey @bmeck, thanks for the awesome project! We use it inside of the [chai-http plugin](https://github.com/chaijs/chai-http) and it works great!

One thing that would be really useful for our users - given that chai-http is a test framework - is to get cookies irrespective of access settings (See [this issue](https://github.com/chaijs/chai-http/issues/43) for more). Perhaps having a sentinel of `Cookie.CookieAccessInfo.All` could be used to flag to `cookie.match()` to automatically return true?

Any thoughts on this would be much appreciated. If you like the idea I'm happy to PR it :smile:

### PR DESCRIPTION
**Pull request by keithamus**
This allows for fetching cookies with any access info, useful for tests.

Fixes #24. Refs chaijs/chai-http#43

Sorry this has taken a while to get done @bmeck

### CODE REVIEW

**Comment by keithamus** [comment]
@bmeck any update on this?

**Comment by bmeck** [comment]
@keithamus change to use `Object.create(null)` and LGTM

**Comment by keithamus** [comment]
@bmeck done and done 😄

**Comment by bmeck** [comment]
merged, will publish to npm after a couple meetings

**Comment by bmeck** [comment]
Published using https://github.com/bmeck/node-cookiejar/commit/f7c331ba0e752a9c834e8fd888bf5270592c6f44

**Pull request merged**
