### PR TITLE
 Better document cookie addition

### PR DESCRIPTION
**Pull request by AmineMenguellat**
Update README file and tests file to better document the cookie addition process, that is the pure cookie appending

### CODE REVIEW

**Comment by madarche** [comment]
Hello @bmeck, any reason not to merge this PR?

**Comment by bmeck** [comment]
Fell under my radar. Merged

**Comment by madarche** [comment]
Thanks @bmeck 😊

**Comment by AmineMenguellat** [comment]
Hello @bmeck thanks you so much  :)

**Pull request merged**
